- name: "people tablosunun oluşturulması"
      mysql_query:
        login_user: berkroot
        login_password: "xxxxxxxxx"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_db: pythonflask
        query: |
          CREATE TABLE IF NOT EXISTS people (
            id INT AUTO_INCREMENT PRIMARY KEY,
            first_name VARCHAR(255) NOT NULL,
            last_name VARCHAR(255) NOT NULL,
            age INT
          );