- name: "pythonflask veritabanının oluşturulması"
      mysql_db:
        login_user: berkroot
        login_password: "xxxxxxxxx"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: pythonflask
        state: present