---
- name: Ensure supervisor is installed
  apt:
    name: supervisor
    state: present
  become: yes

- name: Ensure log directory exists
  file:
    path: /var/log/flaskapp
    state: directory
    mode: '0775'
  become: yes

- name: Set permissions for the log directory
  file:
    path: /var/log/flaskapp
    mode: '0775'
    recurse: yes
  become: yes
