- name: Veritabanı ve kullanıcı oluşturulması
      mysql_user:
        login_user: root
        login_password: "xxxxxx"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: berkroot
        password: "xxxxxxxxxxx"
        host: '%'
        priv: '*.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,RELOAD,SHUTDOWN,PROCESS,FILE,REFERENCES,INDEX,ALTER,SHOW DATABASES,SUPER,CREATE TEMPORARY TABLES,LOCK TABLES,EXECUTE,REPLICATION SLAVE,REPLICATION CLIENT,CREATE VIEW,SHOW VIEW,CREATE ROUTINE,ALTER ROUTINE,CREATE USER,EVENT,TRIGGER,CREATE TABLESPACE,GRANT OPTION'
        state: present